Vagrant.configure("2") do |config|

    config.vm.define "scriptbox" do |scriptbox|
      scriptbox.vm.box = "almalinux/9"
      scriptbox.ssh.username = "vagrant"
      scriptbox.ssh.password = "vagrant"
      scriptbox.ssh.forward_agent = true
      scriptbox.vm.network "private_network", ip: "192.168.56.15"
      scriptbox.vm.hostname = "scriptbox"
      scriptbox.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
     end
    end
  
    config.vm.define "web01" do |web01|
      web01.vm.box = "almalinux/9"
      web01.ssh.username = "vagrant"
      web01.ssh.password = "vagrant"
      web01.ssh.forward_agent = true
      web01.vm.network "private_network", ip: "192.168.56.13"
          web01.vm.hostname = "web01"
    end
    
    config.vm.define "web02" do |web02|
      web02.vm.box = "almalinux/9"
      web02.ssh.username = "vagrant"
      web02.ssh.password = "vagrant"
      web02.ssh.forward_agent = true
      web02.vm.network "private_network", ip: "192.168.56.14"
          web02.vm.hostname = "web02"
    end
  
     config.vm.define "web03" do |web03|
      web03.vm.box = "ubuntu/bionic64"
      web03.ssh.username = "vagrant"
      web03.ssh.forward_agent = true
          web03.vm.network "private_network", ip: "192.168.56.12"
          web03.vm.hostname = "web03"
    end
  end